<?php
/**
* Implementation of hook_menu().
*/
function ajax_articles_menu() {
  $items['get/ajax'] = array(
    'page callback' => 'ajax_articles_ajax_get_ajax', // Render HTML
    // 'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'ajax_articles_ajax_callback',  // Magic goes here
  );
  return $items;
}

function ajax_articles_ajax_get_ajax($nid) {
  // Just load a node and return teaser, you can return whatever you want including forms
  // $node = node_load($nid);
  // return node_view($node, 'teaser');
  // The function will receive the array of arguments after the "get/ajax" prefix
  $path = implode('/', func_get_args());
  $render_string = menu_execute_active_handler($path, FALSE);
  return $render_string;
}

function ajax_articles_ajax_callback($page_callback_result) {
  // Only render content
  // $content = drupal_render($page_callback_result);
  // Only render content and validates return
  $content = is_string($page_callback_result) ? $page_callback_result : drupal_render($page_callback_result);
  // Add CSS and JS files, add some markup
  $html = '<html><head><title></title>' . drupal_get_css() . drupal_get_js() . '</head><body class="jquery-ajax-load">' . $content . '</body></html>';
  print $html;

  // Perform end-of-request tasks.
  drupal_page_footer();
}
